export const workAvailability = [
    {value: 0, label: '18 hours a day - 7 days a week'},
    {value: 1, label: '14 hours a day - 7 days a week'},
    {value: 2, label: '10 hours a day - 7 days a week'},
    {value: 3, label: '8 hours a day - 7 days a week'},
    {value: 4, label: '4 hours a day - 7 days a week'},
    {value: 5, label: '18 hours a day - 6 days a week'},
    {value: 6, label: '14 hours a day - 6 days a week'},
    {value: 7, label: '10 hours a day - 6 days a week'},
    {value: 8, label: '8 hours a day - 6 days a week'},
    {value: 9, label: '4 hours a day - 6 days a week'},
    {value: 10, label: '18 hours a day - 4 days a week'},
    {value: 11, label: '14 hours a day - 4 days a week'},
    {value: 12, label: '10 hours a day - 4 days a week'},
    {value: 13, label: '8 hours a day - 4 days a week'},
    {value: 14, label: '4 hours a day - 4 days a week'},
]
export const timeAvailability = [
    {value:0,label:'06 AM - 10 AM'},
    {value:1,label:'10 AM - 02 AM'},
    {value:2,label:'02 AM - 06 AM'},
    {value:3,label:'06 AM - 10 AM'},
    {value:4,label:'10 AM - 02 AM'},
    {value:5,label:'02 AM - 06 AM'},
    {value:6,label:'Other'},
]
export const educAttainment = [
    {value: 0, label: 'None'},
    {value: 1, label: 'High School'},
    {value: 2, label: 'Associate'},
    {value: 3, label: 'Bachelor'},
    {value: 4, label: 'Master'},
    {value: 5, label: 'Doctor'},
]
export const citations = [
    {value: 0, label: 'MLA'},
    {value: 1, label: 'APA'},
    {value: 2, label: 'Chicago/Turabian'},
    {value: 3, label: 'Harvard'},
    {value: 4, label: 'Other'},
]
export const services = [
    {value: 0, label: 'Writing from scratch'},
    {value: 1, label: 'Editing/ Proofreading'},
    {value: 2, label: 'PowerPoint/ Project'},
    {value: 3, label: 'Ratting writers or student'},
    {value: 4, label: 'Excel'},
    {value: 5, label: 'Access'},
    {value: 6, label: 'Multiple Choices'},
    {value: 7, label: 'Problem Solving'},
    {value: 8, label: 'Other'},
]
export const acadLevel = [
    {value: 0, label: 'High School'},
    {value: 1, label: 'Undergraduate'},
    {value: 2, label: 'Bachelor'},
    {value: 3, label: 'Master'},
    {value: 4, label: 'PhD'},
    {value: 5, label: 'Other'},
]
export const papers = [
    {value: 0, label:'Argumentative Essay'},
    {value: 1, label:'Research Paper'},
    {value: 2, label:'Annotated Bibligraphy'},
    {value: 3, label:'Article Review'},
    {value: 4, label:'Movie Review'},
    {value: 5, label:'Creative Writing'},
    {value: 6, label:'Critical Thinking'},
    {value: 7, label:'Presentation or Speech Research Proposal'},
    {value: 8, label:'Term Paper'},
    {value: 9, label:'Thesis/Dissertation chapter'},
    {value: 10 ,label:'PowerPoint'},
    {value: 11 ,label:'Article'},
    {value: 12 ,label:'Article review'},
    {value: 13 ,label:'Biography'},
    {value: 14 ,label:'Book review'},
    {value: 15 ,label:'Business plan'},
    {value: 16 ,label:'Case study '},
    {value: 17 ,label:'Course work'},
    {value: 18 ,label:'Critical thinking'},
    {value: 19 ,label:'Presentation'},
    {value: 20 ,label:'Report'},
    {value: 21 ,label:'Research Paper'},
    {value: 22 ,label:'Research Proposal'},
    {value: 23 ,label:'Term paper'},
    {value: 24 ,label:'Thesis proposal'},
    {value: 25 ,label:'Outliine'},
    {value: 26 ,label:'Dissertation (Any Type)'},
    {value: 27 ,label:'Dissertation chapter'},
    {value: 28 ,label:'Dissertation conclusion'},
    {value: 29 ,label:'Dissertation hypothesis'},
    {value: 30 ,label:'Dissertation introduction'},
    {value: 31 ,label:'Dissertation methodology'},
    {value: 32 ,label:'Dissertation proposal'},
    {value: 33 ,label:'Dissertation results'},
    {value: 34 ,label:'Questions & Problems'},
    {value: 35 ,label:'Multiple choice questions'},
    {value: 36 ,label:'Problem solving'},
    {value: 37 ,label:'Admissions (Ary type)'},
    {value: 38 ,label:'Admission essay '},
    {value: 39 ,label:'Application letter'},
    {value: 40 ,label:'Cover letter'},
    {value: 41 ,label:'Court letter'},
    {value: 42 ,label:'Curriculum Vitae'},
    {value: 43 ,label:'Personal statement'},
    {value: 44 ,label:'Other'},
]
export const easiestSubject = [
    {value: 0 ,label:'Argumentative Essay'},
    {value: 1 ,label:'Research Paper'},
    {value: 2 ,label:'Annotated Bibliography'},
    {value: 3 ,label:'Article Review'},
    {value: 4 ,label:'Creative Review'},
    {value: 5 ,label:'Critical Thinking'},
    {value: 6 ,label:'Presentation or speech'},
    {value: 7 ,label:'Research Proposal'},
    {value: 8 ,label:'Term Paper'},
]