export const workAvailability = [
    {value: 0, label: '18 hours a day - 7 days a week'},
    {value: 1, label: '14 hours a day - 7 days a week'},
    {value: 2, label: '10 hours a day - 7 days a week'},
    {value: 3, label: '8 hours a day - 7 days a week'},
    {value: 4, label: '4 hours a day - 7 days a week'},
    {value: 5, label: '18 hours a day - 6 days a week'},
    {value: 6, label: '14 hours a day - 6 days a week'},
    {value: 7, label: '10 hours a day - 6 days a week'},
    {value: 8, label: '8 hours a day - 6 days a week'},
    {value: 9, label: '4 hours a day - 6 days a week'},
    {value: 10, label: '18 hours a day - 4 days a week'},
    {value: 11, label: '14 hours a day - 4 days a week'},
    {value: 12, label: '10 hours a day - 4 days a week'},
    {value: 13, label: '8 hours a day - 4 days a week'},
    {value: 14, label: '4 hours a day - 4 days a week'},
]
export const timeAvailability = [
    {value:0,label:'06 AM - 10 AM'},
    {value:1,label:'10 AM - 02 AM'},
    {value:2,label:'02 AM - 06 AM'},
    {value:3,label:'06 AM - 10 AM'},
    {value:4,label:'10 AM - 02 AM'},
    {value:5,label:'02 AM - 06 AM'},
    {value:6,label:'Other'},
]
export const educAttainment = [
    {value: 0, label: 'None'},
    {value: 1, label: 'High School'},
    {value: 2, label: 'Associate'},
    {value: 3, label: 'Bachelor'},
    {value: 4, label: 'Master'},
    {value: 5, label: 'Doctor'},
]
export const citations = [
    {value: 0, label: 'MLA'},
    {value: 1, label: 'APA'},
    {value: 2, label: 'Chicago/Turabian'},
    {value: 3, label: 'Harvard'},
    {value: 4, label: 'Other'},
]
export const services = [
    {value: 0, label: 'Writing from scratch'},
    {value: 1, label: 'Editing/ Proofreading'},
    {value: 2, label: 'PowerPoint/ Project'},
    {value: 3, label: 'Ratting writers or student'},
    {value: 4, label: 'Excel'},
    {value: 5, label: 'Access'},
    {value: 6, label: 'Multiple Choices'},
    {value: 7, label: 'Problem Solving'},
    {value: 8, label: 'Other'},
]
export const acadLevel = [
    {value: 0, label: 'High School'},
    {value: 1, label: 'Undergraduate'},
    {value: 2, label: 'Bachelor'},
    {value: 3, label: 'Master'},
    {value: 4, label: 'PhD'},
    {value: 5, label: 'Other'},
]
export const papers = [
    {value: 0, label:'Argumentative Essay'},
    {value: 1, label:'Research Paper'},
    {value: 2, label:'Annotated Bibligraphy'},
    {value: 3, label:'Article Review'},
    {value: 4, label:'Movie Review'},
    {value: 5, label:'Creative Writing'},
    {value: 6, label:'Critical Thinking'},
    {value: 7, label:'Presentation or Speech Research Proposal'},
    {value: 8, label:'Term Paper'},
    {value: 9, label:'Thesis/Dissertation chapter'},
    {value: 10 ,label:'PowerPoint'},
    {value: 11 ,label:'Article'},
    {value: 12 ,label:'Article review'},
    {value: 13 ,label:'Biography'},
    {value: 14 ,label:'Book review'},
    {value: 15 ,label:'Business plan'},
    {value: 16 ,label:'Case study '},
    {value: 17 ,label:'Course work'},
    {value: 18 ,label:'Critical thinking'},
    {value: 19 ,label:'Presentation'},
    {value: 20 ,label:'Report'},
    {value: 21 ,label:'Research Paper'},
    {value: 22 ,label:'Research Proposal'},
    {value: 23 ,label:'Term paper'},
    {value: 24 ,label:'Thesis proposal'},
    {value: 25 ,label:'Outliine'},
    {value: 26 ,label:'Dissertation (Any Type)'},
    {value: 27 ,label:'Dissertation chapter'},
    {value: 28 ,label:'Dissertation conclusion'},
    {value: 29 ,label:'Dissertation hypothesis'},
    {value: 30 ,label:'Dissertation introduction'},
    {value: 31 ,label:'Dissertation methodology'},
    {value: 32 ,label:'Dissertation proposal'},
    {value: 33 ,label:'Dissertation results'},
    {value: 34 ,label:'Questions & Problems'},
    {value: 35 ,label:'Multiple choice questions'},
    {value: 36 ,label:'Problem solving'},
    {value: 37 ,label:'Admissions (Ary type)'},
    {value: 38 ,label:'Admission essay '},
    {value: 39 ,label:'Application letter'},
    {value: 40 ,label:'Cover letter'},
    {value: 41 ,label:'Court letter'},
    {value: 42 ,label:'Curriculum Vitae'},
    {value: 43 ,label:'Personal statement'},
    {value: 44 ,label:'Other'},
]
export const subjectLabels = [
    "Choose easiest type of paper for you:",
    "Choose 2nd easiest type of paper for you:",
    "Choose 3rd easiest type of paper for you:",
    "Choose 4th easiest type of paper for you:",
    "Choose 5th easiest type of paper for you:",
]
export const easiestSubject = [
    {value: 0 ,label:'Argumentative Essay'},
    {value: 1 ,label:'Research Paper'},
    {value: 2 ,label:'Annotated Bibliography'},
    {value: 3 ,label:'Article Review'},
    {value: 4 ,label:'Creative Review'},
    {value: 5 ,label:'Critical Thinking'},
    {value: 6 ,label:'Presentation or speech'},
    {value: 7 ,label:'Research Proposal'},
    {value: 8 ,label:'Term Paper'},
]
export const rateLabels = [
    "Writing High School paper! I am:",
    "Writing Undergraduate paper! I am:",
    "Writing Bachelor paper! I am:",
    "Writing Master paper! I am:",
    "Writing PhD paper! I am:",
]
export const pagePerDay = [
    "1 Page",
    "2 Pages",
    "3 Pages",
    "4 Pages",
    "5 Pages",
    "6 Pages",
    "7 Pages",
    "8 Pages",
    "9 Pages",
    "10 Pages",
    "11 Pages",
    "12 Pages",
    "13 Pages",
    "14 Pages",
    "15 Pages",
    "16 Pages",
    "17 Pages",
    "18 Pages",
    "19 Pages",
    "20 Pages",
    "21 Pages",
    "22 Pages",
    "23 Pages",
    "24 Pages",
    "25 Pages",
    "26 Pages",
    "27 Pages",
    "28 Pages",
    "29 Pages",
    "30 Pages",
    "31 Pages",
    "32 Pages",
    "33 Pages",
    "34 Pages",
    "35 Pages",
    "36 Pages",
    "37 Pages",
    "38 Pages",
    "39 Pages",
    "40 Pages",
    "41 Pages",
    "42 Pages",
    "43 Pages",
    "44 Pages",
    "45 Pages",
    "46 Pages",
    "47 Pages",
    "48 Pages",
    "49 Pages",
    "50 Pages",
    "51 Pages",
    "52 Pages",
    "53 Pages",
    "54 Pages",
    "55 Pages",
    "56 Pages",
    "57 Pages",
    "58 Pages",
    "59 Pages",
    "60 Pages",
    "61 Pages",
    "62 Pages",
    "63 Pages",
    "64 Pages",
    "65 Pages",
    "66 Pages",
    "67 Pages",
    "68 Pages",
    "69 Pages",
    "70 Pages",
    "71 Pages",
    "72 Pages",
    "73 Pages",
    "74 Pages",
    "75 Pages",
    "76 Pages",
    "77 Pages",
    "78 Pages",
    "79 Pages",
    "80 Pages",
    "81 Pages",
    "82 Pages",
    "83 Pages",
    "84 Pages",
    "85 Pages",
    "86 Pages",
    "87 Pages",
    "88 Pages",
    "89 Pages",
    "90 Pages",
    "91 Pages",
    "92 Pages",
    "93 Pages",
    "94 Pages",
    "95 Pages",
    "96 Pages",
    "97 Pages",
    "98 Pages",
    "99 Pages",
    "100 Pages",
]
export const siteRecommend = [
    {value: 0, label: 'Search engine'},
    {value: 1, label: 'Google ads'},
    {value: 2, label: 'Facebook'},
    {value: 3, label: 'Recommendation'},
    {value: 4, label: 'Other'},
]
export const confirmInfo = [
    {value: 0, label: 'Yes'},
    {value: 1, label: 'No'},
]